config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'customers/registrations'
  }
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'


  resources :centers, except: :index do
    resources :bookings, only: :index # calendar view
    resources :treatments, only: [:new, :create]
  end

  resources :treatments, only: [:index, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :payments, only: :new

    resources :reviews, only: [:new, :create]
  end

  resource :autocomplete, only: :show

  resources :searches, only: :index, path: :search

  get "/results", to: "pages#results"

  get 'pages/help', to: 'pages#help'
end

app/models/center.rb
class Center < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :treatments
  has_many :bookings, through: :treatments
  has_many :reviews, through: :bookings

  belongs_to :owner, class_name: 'User'
  has_many :photos, as: :imageable
  # accepts_nested_attributes_for :photos


  def no_of_reviews
    amount = rand(2..30)
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  def index
    @centers = current_user.centers
    authorize @centers
  end

  def show
    @center = Center.find(params[:id])
    @center.photos.build
    authorize @center
    @treatments = Treatment.where(center: @center)
    @review = Review.new
    @reviews = @center.reviews

    @user_booked_treatments = current_user.bookings.map { |booking| booking.treatment }

    @marker =
      {
        lat: @center.latitude,
        lng: @center.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { center: @center }),
        image_url: helpers.asset_url('abc.png')
      }
  end

  def new
    @center = Center.new
    authorize @center
  end

  def create
    @center = Center.new(safe_params)
    authorize @center
    @center.owner_id = current_user.id
    if @center.save
      redirect_to center_path(@center)
    else
      render :new
    end
  end

  def update
    @center = Center.find(params[:id])
    authorize @center
    if @center.update(safe_params)
      redirect_to @center
    else
      render :show
    end
  end

  def edit
    @center = Center.find(params[:id])
    authorize @center
  end

  def destroy
    @center = Center.find(params[:id])
    authorize @center
    @center.destroy
    @center = current_user.centers
  end

  private

  def safe_params
    params.require(:center).permit(:name, :address, :contact_person, photos_attributes: [:id, :attachment, :attachment_cache])
  end
end

app/views/centers/edit.html.erb
<div>
  <%= simple_form_for (@center) do |f| %>
  <%= f.input :name %>
  <%= f.input :contact_person %>
  <%= f.input :address %>
  <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/centers/index.html.erb
<h1 class="text-center bg-white">All Treatments</h1>
<div class="d-flex p-2 bd-highlight">
  <div class="card-container">
    <% @centers.each do |center| %>
    <div class="treatment-centre-card-product">
      <div class="centre-card-details1">
        <div class="treatment-centre-card-product-infos">
          <div class="treatment-centre-card-product-infos-text">
            <p><%= link_to center.center_name.upcase, center_path(center.id)%></p>
            <p><%= center.address.capitalize %></p>
            <% if policy(center).update? %>
            <%= link_to 'Edit', edit_treatment_path(center) %>
            <% end %>
            <% if policy(center).destroy? %>
            <%= link_to '', center, method: :delete, data: {confirm: "Are you sure?"}, class: "fa fa-trash" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="centre-card-details">
        <div class="centre-card-price">
          <p><%= center.name.capitalize %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

app/views/centers/new.html.erb
<div> <%= render 'shared/center_page_form' %>  </div>

app/views/centers/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@center.photos.first&.attachment&.url || "default-thumb_qpqfou.png" )%>)">
  <div class="container">
    <div class="center-page">
      <h1 class= "text-light font-weight-bold"><%= @center.name %></h1>
      <p class= "text-light font-weight-normal"><%= @center.address%></p>
      <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half"></i><p class= "text-light font-weight-light-small"> <%= @center.no_of_reviews %> Reviews</p>
     <% if  user_signed_in? && current_user.owner?  %>
    <% else %>
    <%= link_to "Book Now", new_treatment_booking_path(@center.treatments.first), class: "btn btn-flat" %>
      <% end %>
    <p class="small font-weight-light font-italic mt-3">Off Peak and Last Minute Slots Available!</p>
      <div class="p-2 flex-shrink-1 bd-highlight"></div>
    </div>
  </div>
</div>
<div class="mt-3 container pt-3 z-depth-1">
  <section class="dark-grey-text border-bottom-light">
    <div class="row">
      <!-- Grid column -->
      <div class="col-lg-6 col-md-12 mb-4">
        <!-- Featured news -->
        <div class="single-news">
          <!-- Image -->
          <div class="view overlay rounded z-depth-1-half mb-4 treatment-img img-fluid">
            <%= cl_image_tag(@center.treatments.first.photos.first&.attachment&.url, class: "treatment-img img-fluid")%>
          </div>
          <div class="view overlay rounded z-depth-1-half mb-4">
          </div>
          <!-- Data -->
          <div class=" d-flex align-items-start ">
           <div class="flex-grow-1"><h6 class="font-weight-bold"><%=@center.treatments.first.name%> </h6>
           <div class="pr-2"><p class="font-weight-light"><%= @center.treatments.first.category %></p></div>

           </div>
              <div class="">
                <% if  user_signed_in? && current_user.owner?  %>
      <%= link_to "Add Treatment", new_center_treatment_path(@center.id), class: "btn-flat" %>
              <% else %>
              <%= link_to "Book Now", new_treatment_booking_path(@center.treatments.first), class: "btn-flat" %>
              <% end %>
              </div>
          </div>
          <!-- Excerpt -->
          <h3 class="font-weight-bold dark-grey-text mb-3"></h3>
          <p class="text-muted font-weight-light">This massage aims to reduce pain by providing you high-quality
            massages tailored to your needs by professional,
            personable and degree-level physiotherapists and
          sports massage therapists.</p>
        </div>
        <!-- Featured news -->
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-lg-6 col-md-12 mb-4 container-treatment-description">
        <!-- Small news -->


        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <div class="col-md-3">
              <!--Image-->
              <div class="view overlay rounded z-depth-1 mb-4">


              </div>
            </div>
            <div class="col-md-9">
              <p class="font-weight-bold grey-text text-uppercase small">OPENING HOURS</p>
              <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Monday</p>
                <p class="font-weight-light">09:00 - 17:00</p>

              </div>

               <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Tuesday</p>
                <p class="font-weight-light">10:00 - 15:00</p>

              </div>
               <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Wednesday</p>
                <p class="font-weight-light">09:00 - 17:00</p>

              </div>
               <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Thursday</p>
                <p class="font-weight-light">09:00 - 17:00</p>

              </div>
               <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Friday</p>
                <p class="font-weight-light">09:00 - 17:00</p>

              </div>
               <div class="d-flex justify-content-between">
                <!-- Excerpt -->
                <p class="text-muted font-weight-light">Saturday</p>
                <p class="font-weight-light">10:00 - 15:00</p>

              </div>

              <div class="d-flex justify-content-between">
                <!-- Excerpt -->

                <%#= link_to "Book", new_center_treatment_booking_path(treatment.center_id, treatment.id), class: "btn-flat" %>

                <p class="text-muted font-weight-light">Sunday</p>
                <p class="font-weight-light">Closed</p>

              </div>

              <div class="d-flex justify-content-between mb-2">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <p class="text-muted font-weight-light"></p>
                </div>
              </div>

            </div>


            <!-- Grid column -->
          </div>

          <!-- Grid row -->

        </div>

        <!-- Small news -->
        <!-- Small news -->
      </div>

      <!--Grid column-->

    </div>

  </div>
  <!-- Grid row -->
</section>

<div class="container">

<!--Accordion wrapper-->
<div class="accordion md-accordion" id="accordionEx1" role="tablist" aria-multiselectable="true">

  <!-- Accordion card -->
  <div class="card">

    <!-- Card header -->
    <div class="card-header p-2" role="tab" id="headingTwo1">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx1" href="#collapseTwo1"
        aria-expanded="false" aria-controls="collapseTwo1">

        <div class="d-flex bd-highlight">
  <div class="p-2 w-100 bd-highlight text-muted"> <h5>Health Treatments</h5> </div>
  <div class="p-2 flex-shrink-1 fas fa-plus text-muted"></div>
</div>

      </a>
    </div>

    <!-- Card body -->
    <div id="collapseTwo1" class="collapse" role="tabpanel" aria-labelledby="headingTwo1"
      data-parent="#accordionEx1">
      <div class="card-body">

        <% @center.treatments.each do |t| %>
          <% if t.category == "Health" %>
        <p class="font-weight-regular"> <%= t.name %></p>
        <p class="text-muted font-weight-bold small"> <%= t.duration %> mins</p>
        <p class= "font-weight-light"> <%= t.description%></p>


        <% if  user_signed_in? && current_user.owner? && current_user.centers.include?(t.center)  %>

        <%= link_to "Edit", edit_treatment_path(t.id), class: "btn btn-ghost mb-2" %>
        <%= link_to "Delete", treatment_path(t.id), class: "btn btn-ghost mb-2", method: :delete %>
        <% else %>
        <%= link_to "Book Now", new_treatment_booking_path(t.id), class: "btn btn-ghost mb-2" %>
        <% end %>

        <%end %>

        <%end  %>

      </div>
    </div>

  </div>
  <!-- Accordion card -->

  <!-- Accordion card -->
  <div class="card">

    <!-- Card header -->
    <div class="card-header p-2" role="tab" id="headingTwo2">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx1" href="#collapseTwo21"
        aria-expanded="false" aria-controls="collapseTwo21">
        <div class="d-flex bd-highlight">
  <div class="p-2 w-100 bd-highlight text-muted"> <h5>Massages</h5> </div>
  <div class="p-2 flex-shrink-1 fas fa-plus text-muted"></div>
</div>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapseTwo21" class="collapse" role="tabpanel" aria-labelledby="headingTwo21"
      data-parent="#accordionEx1">
      <div class="card-body">
        <% @center.treatments.each do |t| %>
          <% if t.category == "Massage" %>
        <p class="font-weight-regular"> <%= t.name %></p>
        <p class="text-muted font-weight-bold small"> <%= t.duration %> mins</p>
        <p class= "font-weight-light"> <%= t.description%></p>


        <% if  user_signed_in? && current_user.owner? && current_user.centers.include?(t.center)  %>


        <%= link_to "Edit", edit_treatment_path(t.id), class: "btn btn-ghost mb-2" %>

        <%= link_to "Delete", treatment_path(t.id), class: "btn btn-ghost mb-2", method: :delete %>
        <% else %>
        <%= link_to "Book Now", new_treatment_booking_path(t.id), class: "btn btn-ghost mb-2" %>
        <% end %>


        <%end  %>

        <%end  %>
      </div>
    </div>

  </div>
  <!-- Accordion card -->

  <!-- Accordion card -->
  <div class="card">

    <!-- Card header -->
    <div class="card-header p-2" role="tab" id="headingThree31">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx1" href="#collapseThree31"
        aria-expanded="false" aria-controls="collapseThree31">
        <div class="d-flex bd-highlight">
  <div class="p-2 w-100 bd-highlight text-muted"> <h5>Spa</h5> </div>
  <div class="p-2 flex-shrink-1 fas fa-plus text-muted"></div>
</div>
      </a>
    </div>

    <!-- Card body -->
    <div id="collapseThree31" class="collapse" role="tabpanel" aria-labelledby="headingThree31"
      data-parent="#accordionEx1">
      <div class="card-body">
         <% @center.treatments.each do |t| %>
          <% if t.category == "Spa" %>
        <p class="font-weight-regular"> <%= t.name %></p>
        <p class="text-muted font-weight-bold small"> <%= t.duration %> mins</p>
        <p class= "font-weight-light"> <%= t.description%></p>


        <% if  user_signed_in? &&  current_user.owner? && current_user.centers.include?(t.center)  %>


        <%= link_to "Edit", edit_treatment_path(t.id), class: "btn btn-ghost mb-2" %>
        <%= link_to "Delete", treatment_path(t.id), class: "btn btn-ghost mb-2", method: :delete %>
        <% else %>
        <%= link_to "Book Now", new_treatment_booking_path(t.id), class: "btn btn-ghost mb-2" %>
        <% end %>

        <%end  %>

        <%end  %>
      </div>
    </div>

  </div>
  <!-- Accordion card -->

</div>
</div>
<!-- Accordion wrapper -->

<!--Section: Content-->
<!--Section: Content-->
<section class="magazine-section mt-3">
  <section class="dark-grey-text">
    <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 mb-4">
            <h4 class="font-weight-normal mb-4">About Us</h4>
            <p class="text-muted font-weight-light">A peaceful sanctuary to relax and leave you feeling refreshed and with a renewed and relaxed mind and body.</p>
            <p class="text-muted font-weight-light"> <%= @center.description  %> </p>
          </div>
          <div class="col-lg-6 mb-4">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100 treatment-img" src="https://i.imgur.com/gNrkLEM.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100 treatment-img" src="https://i.imgur.com/u49tpiT.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100 treatment-img" src="https://i.imgur.com/ki3RdWP.jpg" alt="Third slide">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
    </div>
  </section>
</section>
<!--Section: Content-->

<!--Section: Content-->
</div>
</div>

<style>
.map-container {
overflow: hidden;
position: relative;
height: 0;
}
.map-container iframe {
left: 0;
top: 0;
height: 100%;
width: 100%;
position: absolute;
}
</style>

<!-- Section: Block Content -->

</div>
<section class="map-section ">
  <section class="dark-grey-text">
    <div class="container map-relative pt-4">
        <div class="row align-items-center">
          <div class="col-12 mb-4">
            <div
        class="px-2 mapboxgl-ctrl-geocoder--input"
        id="map"
        style="width: 100%;
        height: 400px;"
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
          </div>
          <div class="align-self-center py-4">
            <div class="map-relative-text">
            <div class="map-text-info">
              <h6 class="font-weight-bold grey-text text-uppercase small"> <%= @center.name %> </h6>
              <p class="text-muted font-weight-light"><%=@center.address%></p>
              <p class="text-muted font-weight-light mb-0">Phone: +39 987 123 6548<br>Email: <%= @center.contact_person.downcase%>@libero.it</p>
            </div>
          </div>
        </div>
    </div>
  </section>
</section>