config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'customers/registrations'
  }
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'


  resources :centers, except: :index do
    resources :bookings, only: :index # calendar view
    resources :treatments, only: [:new, :create]
  end

  resources :treatments, only: [:index, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :payments, only: :new

    resources :reviews, only: [:new, :create]
  end

  resource :autocomplete, only: :show

  resources :searches, only: :index, path: :search

  get "/results", to: "pages#results"

  get 'pages/help', to: 'pages#help'
end

app/views/shared/_center-form.html.erb
<div class="container py-3 ">
  <div class="modal-card-smaller p-3">
    <div>
      <h1 class="mx-3 my-3"> Register your center </h1>
      <div>
        <%= simple_form_for (@center) do |f| %>
        <%= f.input :center_name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :contact_person %>
        <%= f.input :address %>
        <%= f.submit "Register now", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/shared/_center_page_form.html.erb
<div class="container py-3 ">
  <div class="modal-card-smaller p-3">
    <div>
      <h1 class="mx-3 my-3"> Edit Your Page </h1>
      <div>
        <%= simple_form_for (@center) do |f| %>
       <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :contact_person %>
        <%= f.simple_fields_for :photos do |p|  %>
          <%= p.input :attachment %>
          <%= p.input :attachment_cache, as: :hidden %>
        <% end %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small unique-color-dark footer-container">

  <div>
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center footer-bar">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0 footer-title">Get connected with us on social networks!</h6>
        </div>

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic footer-title">
            <i class="fab fa-facebook-f white-text mr-4 footer-title"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4 footer-title"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4 footer-title"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4 footer-title"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text footer-title"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5 ">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold footer-title">About Us</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto footer-title" style="width: 60px;">
        <p class="footer-title">Are you looking for a location or treatment to regenerate and escape from everyday stress?<br>
Aspa is the 1st online reservation portal for wellness.
Find a wellness center or spa in your city <br>
Choose from over 187 000 centers.<br> Read reviews from other customers.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-title">Our solution for your Center</h6>
        <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="footer-title" href="#!">Digital calendar to manage reservations</a>
        </p>
        <p>
          <a class="footer-title" href="#!">Economic management</a>
        </p>
        <p>
          <a class="footer-title" href="#!">Automatic promotional campaigns</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-title">Useful links</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="footer-title" href="#!">Register your center</a>
        </p>
        <p>
          <a class="footer-title" href="#!">Sign up</a>
        </p>
        <p>
          <a class= "footer-title" href="#!">Login</a>
        </p>
        <p>
          <a class="footer-title" href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-title">Contact</h6>
        <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px white;">
        <p>
          <i class="fas fa-home mr-3 footer-title"></i> Milan, MI, ITALY</p>
        <p>
          <i class="fas fa-envelope mr-3 footer-title"></i> info@aspawellness.com</p>
        <p>
          <i class="fas fa-phone mr-3 footer-title "></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3 footer-title "></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 footer-title">© 2019 Copyright:
    <a class="footer-title" href="https://mdbootstrap.com/education/bootstrap/"> Aspa Group s.r.l.</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to (image_tag("circle-cropped.png")), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if  user_signed_in? && current_user.owner?  %>
        <li class="nav-item navbar-lewagon">
          <%= link_to "My Profile", center_path(@my_center), class: "nav-link font-weight-light " %>
        </li>
      <% end %>
      <% if user_signed_in? && current_user.customer? %>
        <li class="nav-item navbar-lewagon">
          <%= link_to "My Bookings", bookings_path, class: "nav-link font-weight-light" %>
        </li>
      <li class="nav-item dropdown">
        <%= image_tag "oma-avatar.png", size:"38x38",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if policy(Center).create? %>
          <%= link_to "Register Your Centre", new_center_path, class: "dropdown-item font-weight-light" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% elsif user_signed_in? && current_user.owner? %>
      <li class="nav-item navbar-lewagon">
        <%= link_to "Calendar", bookings_path, class: "nav-link font-weight-light" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "centerprofileavatar.png", size:"38x38",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Register Your Centre", new_center_path, class: "dropdown-item font-weight-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Register Your Centre", new_center_path, class: "nav-link font-weight-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link font-weight-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link font-weight-light" %>
      </li>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-trasparent">
  <%= link_to (image_tag("circle-cropped.png")), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if  user_signed_in? && current_user.owner?  %>
      <%= link_to "My Profile", center_path(@my_center), class: "nav-link white-link font-weight-light" %>
      <% end %>
      <% if user_signed_in? && current_user.customer? %>
      <li class="nav-item navbar-lewagon white-link">
        <%= link_to "My Bookings", bookings_path, class: "nav-link white-link font-weight-light " %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "oma-avatar.png", size:"38x38",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if policy(Center).create? %>
          <%= link_to "Register Your Centre", new_center_path, class: "dropdown-item font-weight-light" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% elsif user_signed_in? && current_user.owner? %>
      <li class="nav-item navbar-lewagon nav-item-text" style="background:none; ">
        <%= link_to "Calendar", bookings_path, class: "nav-link white-link font-weight-light" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "centerprofileavatar.png", size:"38x38",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Register Your Centre", new_center_path, class: "dropdown-item font-weight-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Register Your Centre", new_center_path, class: "nav-link white-link font-weight-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link white-link font-weight-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link white-link font-weight-light" %>
      </li>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item font-weight-light" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_no-results.html.erb
<div class="container-no-result" style="height: 70vh; text-align: center; display: flex;">
  <div style="margin:auto; align-items: center;">
  <h1 style="margin-bottom: 20px;">Sorry, we could not find any results</h1>
  <%= link_to 'Back to home page', root_path, class: "btn-flat" %>
  </div>
</div>

app/views/shared/_opening_hours_form.html.erb
<%= form_with(model: @slot, html: { class: 'card form' }) do |form| %>
  <section class="datetime section">
    <fieldset class="datepicker">
      <%= form.label :start_time, 'Date' %>
      <%= form.text_field :start_time, id: 'date' %>
    </fieldset>
  </section>
<% end %>

app/views/shared/_search-form.html.erb
<div class="search-form">
<%= form_tag searches_path, method: :get,
                            data: {
                                controller: "autocomplete",
                                autocomplete_url: autocomplete_path
                            } do %>
  <%= text_field_tag :treatment,
    params[:treatment],
    class: "form-control input-search-form",
    placeholder: "Choose your treatment",
    data: {
      target: "autocomplete.input"
    }
  %>
  <ul data-target="autocomplete.results" class="list-group"></ul>
  <%= text_field_tag :address,
    params[:address],
    class: "form-control input-search-form flat_address",
    placeholder: "Choose the city"
  %>
  <%= submit_tag "Search Now", class: "btn btn-flat mt-2" %>
<% end %>
</div>