config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'customers/registrations'
  }
  root to: 'pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'


  resources :centers, except: :index do
    resources :bookings, only: :index # calendar view
    resources :treatments, only: [:new, :create]
  end

  resources :treatments, only: [:index, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show] do
    resources :payments, only: :new

    resources :reviews, only: [:new, :create]
  end

  resource :autocomplete, only: :show

  resources :searches, only: :index, path: :search

  get "/results", to: "pages#results"

  get 'pages/help', to: 'pages#help'
end

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(42,57,77,0.4)), url(https://res.cloudinary.com/dbgxzafez/image/upload/v1575303401/Almablu-Wellness-Spa_oapmrf.jpg);">
  <%= render 'shared/navbar_home' %>
  <div class="flexando">
    <div class="container-search margin-left">
      <h1>Search<strong> your</strong> amazing <strong>wellness experience</strong>!</h1>
      <p>Search, book, and live a unique experience..</p>
      <%= render 'shared/search-form' %>
    </div>
  </div>
</div>
<section>
  <h2 class="card-title margin-left mt-3">Explore Treatments</h2>
</section>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(42,57,77,0.4)), url(https://res.cloudinary.com/dbgxzafez/image/upload/v1575306822/estheclinic-slimming_kxjr66.jpg)">
    <%= link_to 'Health Treatments', treatments_path(:category => "Health"), class: "card-category-link" %>
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(42,57,77,0.4)), url(https://res.cloudinary.com/dbgxzafez/image/upload/v1575303401/spa-wellness-green-park-madama-1_y0tpwx.jpg)">
    <%= link_to 'Spa', treatments_path(:category => "spa"), class: "card-category-link" %>
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(42,57,77,0.4)), url(https://res.cloudinary.com/dbgxzafez/image/upload/v1575306450/andergassen-web-1056_yiekir.jpg)">
    <%= link_to 'Massage', treatments_path(:category => "Massage"), class: "card-category-link" %>
  </div>
</div>
<div class="banner-present" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(42,57,77,0.4)), url(https://res.cloudinary.com/dbgxzafez/image/upload/v1575303401/spa-wellness-green-park-madama-1_y0tpwx.jpg);">
  <div class="container.present margin-left">
    <h1>Your wellness gift </h1>
    <p>Give a special experience to your special person.</p>
    <a class="btn btn-flat" href="#">Make a gift</a>
  </div>
</div>
<section>
  <h2 class="card-title margin-left mt-3">Choose your wellness experience.</h3>
  <p class="card-subtitle margin-left">Are you looking for a location or treatment to regenerate and escape from everyday stress?</p>
</section>
<section class="m-2">
  <div class="row">
    <%  @centers.each do |c| break if c.id > 4 %>
    <div class="col-12 col-md-6">
      <div class="card shadow-border mt-3">
        <div class="card-category " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(42,57,77,0.4)), url(<%= cl_image_path c.photos.first&.attachment&.url || "default-thumb_qpqfou.png"  %>)"></div>
        <div class="card-body">
          <h3 class="center-card-title"><%= c.name %></h3>
          <p class="card-text text-truncate"><%= c.description %></p>
          <%= link_to "Show Center", center_path(c.id), class:"btn btn-ghost btn-position" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>
</div>
<!-- Footer -->